settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: negocios-dev.juana.house # unique identifier
    name: negocios-dev.juana.house
    description: 'Panel Negocios - Dev' # default=empty
    url: 'https://negocios-dev.juana.house/login' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: negocios.juana.house # unique identifier
    name: negocios.juana.house
    description: 'Panel Negocios' # default=empty
    url: 'https://negocios.juana.house/login' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: lacasadejuana.cl
    name: lacasadejuana.cl
    description: 'CMS'
    url: 'https://lacasadejuana.cl'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: 'admin.juana.house'
    name: 'admin.juana.house'
    description: 'CMS'
    url: 'https://admin.juana.house'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
